[platformio]
default_envs = stm32f070f6p6

[env:stm32f070f6p6]
platform = ststm32@19.7.1
board = stm32f070f6p6
framework = stm32cube
upload_protocol = stlink
build_flags =
    -std=gnu++17
    -Os
    -ffunction-sections
    -fdata-sections
build_src_flags =
    -Wall
    -Wextra
    -Wpedantic
    -Werror

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -Wpedantic
    -Werror
