recording:
  out_dir: ./recordings
  jpg_quality: 90
  save_depth: false
  imu_bin: true

units:
  - name: left_hand
    role: realtime_vio
    imu:
      port: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_f6a5f836b505f011ae3b8c1272aab386-if00-port0
      baud: 921600
      protocol: stm32_combined_v1
      calibration: ""
    camera:
      serial: "260322273737"
      width: 1280
      height: 720
      fps: 30
      enable_depth: false
      stereo_ir: true
      rgb_preview: true
      auto_exposure: true
      auto_exposure_limit_us: 8000
      auto_gain_limit: 248
      exposure_us: 20000
      gain: 48
      cam_latency_ms: 0.0
    vio:
      backend: vins_fusion_ros2
      cam_topic: /cam0/image_raw
      cam1_topic: /cam1/image_raw
      imu_topic: /imu0
      odom_topic: /odometry_rect
      stereo: true
      port: 100
      qos_reliable: true
