inherit: "/home/robot/ego_vio_humble/config/mast3r_slam_d405_offline.yaml"

tracking:
  stereo_pointmap_scale_prior: True
  stereo_fix_pose_scale: True
  stereo_pointmap_depth_anchor: True
  stereo_preserve_keyframe_pointmap: True
  stereo_keyframe_pnp: True
  stereo_keyframe_3d_translation_refine: True
  stereo_scale_min_confidence: 1.0
  stereo_scale_max_relative_jump: 1.0
